---
title: "Ion Morbility Particle Size Boxplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "Home", 
                href: "../../../docs/hdl.html", 
                align: left }
        source_code: embed
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT',
         'ggsci', 'Metabase')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load("../Rdata/imb_precalc.Rdata")
```

Column
--------------------------

###

```{r}
renderPlotly({
    p = plot_boxplot(ion_morbility, 
                     x = "Timepoint", 
                     feature = feature_selector(),
                     cols = "Treatment",
                     line = "Subject",
                     color = "Subject",
                     color.pal = pal_jama()(7)) +
        labs(x = "")
    ggplotly(p)
})
```

Column
--------------------------

###

```{r}
stats_table = limma_result %>%
        rownames_to_column("Feature") %>%
        arrange(P.Value) %>%
        mutate(
            logFC = round(logFC, digits = 3),
            AveExpr = round(logFC, digits = 3),
            t = round(t, digits = 3),
            P.Value = round(P.Value, digits = 3),
            adj.P.Val = round(adj.P.Val, digits = 3),
            B = round(B, digits= 3)
        )%>%
        column_to_rownames("Feature")

output$stats_table = renderDataTable(
    stats_table, 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selector = reactive({
    rownames(stats_table)[input$stats_table_rows_selected]
})
dataTableOutput("stats_table")
```