---
title: "Lipidomics Feature Boxplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "Home", 
                href: "../../../docs/hdl.html", 
                align: left }
        source_code: embed
runtime: shiny 
---

<style>
.datatables{
    overflow: auto
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('dplyr','stringr','reshape2','tibble', 'plotly', 'DT', 'Metabase','ggsci')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load('../Rdata/lpd_precalc.Rdata')
```

```{r input panel}
inputPanel(
    selectInput('level', "Select Lipid Class or Species:",
                choices = names(lipidome_set), selected = "species"),
    selectInput('normal', 'Select a Normalization Method:',
                choices = names(lipidome_set[[1]]), selected = "Concentration")
)
```

Column 
-------------------------------------
    
### Boxplot

```{r}
renderPlotly({
    mset = lipidome_set[[input$level]][[input$normal]]
    p = plot_boxplot(mset, 
                     x = "Timepoint", 
                     feature = feature_selector(),
                     cols = "Treatment",
                     line = "Subject",
                     color = "Subject",
                     color.pal = pal_jama()(7)) +
        labs(x = "")
    ggplotly(p)
})

```


Column
-------------------------------------

### Stats Table

```{r}
stats_table = reactive({
    limma_list[[input$level]][[input$normal]] %>%
        rownames_to_column("Feature") %>%
        arrange(P.Value) %>%
        mutate(
            logFC = round(logFC, digits = 3),
            AveExpr = round(logFC, digits = 3),
            t = round(t, digits = 3),
            P.Value = round(P.Value, digits = 3),
            adj.P.Val = round(adj.P.Val, digits = 3),
            B = round(B, digits= 3)
        )%>%
        column_to_rownames("Feature")
}) 
output$stats_table = renderDataTable(
    stats_table(), 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selector = reactive({
    rownames(stats_table())[input$stats_table_rows_selected]
})
dataTableOutput("stats_table")
```