---
title: "Exploratory HDL LDL vs Chol Efflux"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "Home", 
                href: "../../site/_site/hdl.html", 
                align: left }
        source_code: embed
        orientation: rows
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT',
         'limma','ggplot2','ggsci')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load("../../diet/Rdata/clinical_precalc.Rdata")
load("../Rdata/fct_precalc.Rdata")
```

```{r}
df1 =data.frame(
    ldl = clinical_data[,"LDL (calc)  (mg/dL)"],
    hdl = clinical_data[,"HDL (mg/dL)"],
    tc = clinical_data[,"Cholesterol total (mg/dL)"],
    chol_efflux = fct_data$`Chol Efflux (ApoB Depleted Serum 1%)`,
    Subj = pdata$Subj,
    TX = pdata$TX,
    Day = pdata$Day
)
df2 = data.frame(
    ldl = clinical_data[,"LDL (calc)  (mg/dL)"],
    hdl = clinical_data[,"HDL (mg/dL)"],
    tc = clinical_data[,"Cholesterol total (mg/dL)"],
    chol_efflux = fct_data$`Chol Efflux (ApoB Depleted Serum 1%)`,
    Subj = pdata$Subj,
    TX = pdata$TX,
    Day = pdata$Day
) %>%
    melt(id.var = c("Subj","TX","Day"),
         variable.name = "lipoprotein",
         value.name = "Value") %>%
    filter(TX == "egg") %>% 
    dcast(Subj + lipoprotein ~ Day, value.var = "Value") %>% 
    mutate(change = Post - Pre) %>%
    dcast(Subj ~ lipoprotein, value.var = "change")
```

Row
---------------------

### HDL

```{r}
p = ggplot(df1, aes(Day, hdl)) +
    geom_boxplot() +
    geom_point(aes(color = Subj),size=2) +
    geom_line(aes(group = Subj, color = Subj)) +
    facet_grid(.~TX) +
    scale_color_manual(values = colorRampPalette(colors=pal_jama()(7))(20)) +
    theme_bw() +
    theme(
        axis.title.x = element_blank()
    )
ggplotly(p)
```

### LDL

```{r}
p = ggplot(df1, aes(Day, ldl)) +
    geom_boxplot() +
    geom_point(aes(color = Subj),size=2) +
    geom_line(aes(group = Subj, color = Subj)) +
    facet_grid(.~TX) +
    scale_color_manual(values = colorRampPalette(colors=pal_jama()(7))(20)) +
    theme_bw() +
    theme(
        axis.title.x = element_blank()
    )
ggplotly(p)
```

### Total Chol

```{r}
p = ggplot(df1, aes(Day, tc)) +
    geom_boxplot() +
    geom_point(aes(color = Subj),size=2) +
    geom_line(aes(group = Subj, color = Subj)) +
    facet_grid(.~TX) +
    scale_color_manual(values = colorRampPalette(colors=pal_jama()(7))(20)) +
    theme_bw() +
    theme(
        axis.title.x = element_blank()
    )
ggplotly(p)
```

Row
--------------------

### Chol Efflux

```{r}
p = ggplot(df1, aes(Day, chol_efflux)) +
    geom_boxplot() +
    geom_point(aes(color = Subj),size=2) +
    geom_line(aes(group = Subj, color = Subj)) +
    facet_grid(.~TX) +
    scale_color_manual(values = colorRampPalette(colors=pal_jama()(7))(20)) +
    theme_bw() +
    theme(
        axis.title.x = element_blank()
    )
ggplotly(p)
```

### HDL vs Chol Efflux

```{r}
p = ggplot(df2, aes(hdl, chol_efflux)) +
    geom_point(aes(color = Subj),size=2) +
    stat_smooth(method = "lm") +
    scale_color_manual(values = colorRampPalette(colors=pal_jama()(7))(20)) +
    theme_bw()
ggplotly(p)
```

### LDL vs Chol Efflux

```{r}
p = ggplot(df2, aes(ldl, chol_efflux)) +
    geom_point(aes(color = Subj),size=2) +
    stat_smooth(method = "lm") +
    scale_color_manual(values = colorRampPalette(colors=pal_jama()(7))(20)) +
    theme_bw()
ggplotly(p)
```