---
title: "Clinical Value Boxplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "Home", 
                href: "../../../docs/diet.html", 
                align: left }
        source_code: embed
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('dplyr','stringr','reshape2','tibble', 'plotly', 'DT',
         'Metabase','ggsci')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load("../Rdata/clinical_precalc.Rdata")
```

Column
--------------------------

###

```{r}
renderPlotly({
    p = plot_boxplot(clinical, x="Timepoint", feature = feature_selector(),
                     cols = "Treatment", line = "Subject", color = "Subject",
                     color.pal = pal_jama()(7))
    ggplotly(p)
})
```

Column
--------------------------

###

```{r}
stats_table = limma_result %>%
    rownames_to_column("Feature") %>%
    arrange(P.Value) %>%
    sapply(function(col){
        if(!is.numeric(col))
            return(col)
        round(col, 3)
    }) %>%
    as.data.frame %>%
    column_to_rownames("Feature")

output$stats_table = renderDataTable(
    stats_table, 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selector = reactive({
    rownames(stats_table)[input$stats_table_rows_selected]
})
dataTableOutput("stats_table")
```