---
title: "Lipidome Data"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "Home", 
                href: "../../site/_site/index.html", 
                align: left }
        source_code: embed
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'data.table', 'DT')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load("../Rdata/lpd_precalc.Rdata")
```

Concentration {data-navmenu="Class"}
============================

```{r}
lipidome_set$class$Concentration$conc_table %>%
    t %>% as.data.frame %>%
    datatable(
        extensions = 'Buttons',
        options = list(
            dom = "Bfrtip",
            pageLength = 40,
            bottons = c("copy","csv","excel")
        )
    ) %>%
    formatRound(columns = featureNames(lipidome_set$class$Concentration),
                digits = 3)
```

Proportion {data-navmenu="Class"}
=====================================

```{r}
lipidome_set$class$Proportion$conc_table %>%
    t %>% as.data.frame %>%
    datatable(
        extensions = 'Buttons',
        options = list(
            dom = "Bfrtip",
            pageLength = 40,
            bottons = c("copy","csv","excel")
        )
    )%>%
    formatRound(columns = rownames(lipidome_set$class$Proportion),
                digits = 3)
```

Concentration {data-navmenu="Species"}
=====================================

```{r}
lipidome_set$feature$Concentration$conc_table %>%
    t %>% as.data.frame %>%
    datatable(
        extensions = 'Buttons',
        options = list(
            dom = "Bfrtip",
            pageLength = 40,
            bottons = c("copy","csv","excel")
        )
    )%>%
    formatRound(columns = featureNames(lipidome_set$feature$Concentration),
                digits = 3)
```

Proportion {data-navmenu="Species"}
=====================================

```{r}
lipidome_set$feature$Proportion$conc_table %>%
    t %>% as.data.frame %>%
    datatable(
        extensions = 'Buttons',
        options = list(
            dom = "Bfrtip",
            pageLength = 80,
            bottons = c("copy","csv","excel")
        )
    )%>%
    formatRound(columns = featureNames(lipidome_set$feature$Proportion),
                digits = 3)
```